[[plugins]]
repo = 'Shougo/dein.vim'
hook_source = '''
let g:dein#install_message_type = "echo"
'''
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  augroup MyColor
    autocmd!
    au ColorScheme * hi Normal ctermbg=black guibg=#000000
    au BufEnter * nested colorscheme iceberg
  augroup END
'''

