[[plugins]]
repo = 'Shougo/dein.vim'
hook_source = '''
let g:dein#install_message_type = "echo"
'''
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  augroup MyColor
    autocmd!
    au BufEnter * nested colorscheme iceberg
    au BufEnter,ColorScheme * highlight Normal ctermbg=232 guibg=#000000
  augroup END
'''
