[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#install_message_type = "echo"
function! DeinInstall() abort
  if dein#check_install()
    call dein#install()
  endif
endfunction

function! DeinClean() abort
  let s:removed_plugins = dein#check_clean()
  if len(s:removed_plugins) > 0
    call map(s:removed_plugins, "delete(v:val, 'rf')")
    call dein#recache_runtimepath()
  endif
endfunction

command! DeinInstall call DeinInstall()
command! DeinClean call DeinClean()
'''
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  augroup MyColor
    autocmd!
    au ColorScheme * hi Normal guibg=#000000
    au ColorScheme * hi SignColumn guibg=#000000
    au ColorScheme * hi GitGutterAdd ctermfg=150 ctermbg=235 guifg=#b4be82 guibg=#000000
    au ColorScheme * hi GitGutterChange ctermfg=109 ctermbg=235 guifg=#89b8c2 guibg=#000000
    au ColorScheme * hi GitGutterChangeDelete ctermfg=109 ctermbg=235 guifg=#89b8c2 guibg=#000000
    au ColorScheme * hi GitGutterDelete ctermfg=203 ctermbg=235 guifg=#e27878 guibg=#000000
    au ColorScheme * hi NormalFloat guibg=#1f2335
    au ColorScheme * hi FloatBorder guifg=white guibg=#1f2335 blend=20
    au ColorScheme * hi Pmenu ctermfg=251 ctermbg=236 guifg=#c6c8d1 guibg=#1f2335 blend=20
    au ColorScheme * hi VertSplit cterm=NONE ctermbg=233 ctermfg=233 gui=NONE guibg=#000000 guifg=#253f4d
  augroup END

  colorscheme iceberg
'''

[[plugins]]
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua require('impatient')
'''

[[plugins]]
repo = 'David-Kunz/treesitter-unit'

[[plugins]]
repo = 'kana/vim-textobj-user'


[[plugins]]
repo ='tpope/vim-repeat'

[[plugins]]
repo ='kana/vim-operator-user'

[[plugins]]
repo = 'vim-denops/denops.vim'
