[[plugins]]
repo = 'Shougo/dein.vim'
hook_source = '''
let g:dein#install_message_type = "echo"
'''
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  augroup MyColor
    autocmd!
    au BufEnter * nested colorscheme iceberg
    au BufEnter,ColorScheme * highlight Normal ctermbg=232 guibg=#000000
  augroup END
'''
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
" <C-w> 系を Vim Tmux Navigator に移譲する
nnoremap <silent> <C-w>h :TmuxNavigateLeft<cr>
nnoremap <silent> <C-w>j :TmuxNavigateDown<cr>
nnoremap <silent> <C-w>k :TmuxNavigateUp<cr>
nnoremap <silent> <C-w>l :TmuxNavigateRight<cr>
nnoremap <silent> <C-w>\\ :TmuxNavigatePrevious<cr>
'''
[[plugins]]
repo = 'junegunn/fzf'
build = '''
./install -all
'''

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = 'denops.vim'
