[ftplugin]
_ = '''
" Disable automatically insert comment.
setl formatoptions-=t
setl formatoptions-=c
setl formatoptions-=r
setl formatoptions-=o
setl formatoptions+=mMBl
" Disable auto wrap.
if &l:textwidth != 70 && &filetype !=# 'help'
  setlocal textwidth=0
endif
if !&l:modifiable
  setlocal nofoldenable
  setlocal foldcolumn=0
  setlocal colorcolumn=
endif
'''
vim = '''
setlocal sw=2 sts=2 ts=2 et
setlocal iskeyword+=:,#
setlocal indentkeys+=\\,endif,endfunction,endfor,endwhile,endtry
let b:echodoc_enabled = v:true
'''

toml = '''
let b:echodoc_enabled = v:true
'''

qfreplace = 'setlocal nofoldenable'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

typescript = '''
setlocal shiftwidth=2
'''

js = '''
setlocal sw=2 sts=2 ts=2 et
'''

yaml = '''
setlocal ts=2 sts=2 sw=2 et
'''

tf = '''
autocmd BufNewFile,BufRead *.tf set filetype=hcl
'''
